name: check-pr-title

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24  # v7.1.1
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Check PR title format
      run: uv run --no-project .github/bin/check-pr-title-format
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
