name: Combine Dependabot PRs

on:
  schedule:
    - cron: '3 10 * * 1-5'  # 10:03 AM UTC, Monday through Friday
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Combine Dependabot PRs
        uses: github/combine-prs@2909f404763c3177a456e052bdb7f2e85d3a7cb3 # v5.2.0
        with:
          ignore_label: "nocombine"
          select_label: dependencies
          labels: "dependencies, combined-pr, no-ticket"
          pr_title: "chore(deps): Combine Dependabot PRs"
