name: pyright

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**/*.py'
      - 'uv.lock'
      - 'pyproject.toml'
  workflow_call:

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e  # v6.8.0
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install dependencies
      run: uv sync --locked --all-extras --dev

    - name: Run pyright
      run: uv run pyright
